name: movie_booking_app
description: A new Flutter application.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_calendar_week: ^3.0.0
  barcode_widget: ^2.0.2
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.2
  json_serializable: ^6.1.4
  json_annotation: ^4.4.0
  http: ^0.13.4
  dio: ^4.0.4
  retrofit: ^3.0.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  flutter_cache_manager: ^3.3.0
  cached_network_image: ^3.0.0
  date_format: ^2.0.5
  google_sign_in: ^5.2.3
  flutter_facebook_auth: ^4.0.1
  intl: ^0.17.0
  stream_transform: ^2.0.0
  provider: ^6.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner:
  retrofit_generator: ^4.0.0
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/